/*
 * generated by Xtext
 */
package com.x.xocl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XOCLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.x.xocl.ui.internal.XOCLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.x.xocl.ui.internal.XOCLActivator.getInstance().getInjector("com.x.xocl.XOCL");
	}
	
}
