/*
* generated by Xtext
*/
package com.x.xocl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.x.xocl.services.XOCLGrammarAccess;

public class XOCLParser extends AbstractContentAssistParser {
	
	@Inject
	private XOCLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.x.xocl.ui.contentassist.antlr.internal.InternalXOCLParser createParser() {
		com.x.xocl.ui.contentassist.antlr.internal.InternalXOCLParser result = new com.x.xocl.ui.contentassist.antlr.internal.InternalXOCLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTopLevelElementAccess().getAlternatives(), "rule__TopLevelElement__Alternatives");
					put(grammarAccess.getVersionStringAccess().getAlternatives(), "rule__VersionString__Alternatives");
					put(grammarAccess.getPackageElementAccess().getAlternatives(), "rule__PackageElement__Alternatives");
					put(grammarAccess.getOnProcessResultAccess().getAlternatives(), "rule__OnProcessResult__Alternatives");
					put(grammarAccess.getWorkflowRolesAccess().getAlternatives(), "rule__WorkflowRoles__Alternatives");
					put(grammarAccess.getEndPointAccess().getAlternatives(), "rule__EndPoint__Alternatives");
					put(grammarAccess.getWorkflowElementAccess().getAlternatives(), "rule__WorkflowElement__Alternatives");
					put(grammarAccess.getWorkflowActionAccess().getAlternatives(), "rule__WorkflowAction__Alternatives");
					put(grammarAccess.getWorkflowRoleReferenceAccess().getAlternatives(), "rule__WorkflowRoleReference__Alternatives");
					put(grammarAccess.getTransactionAccess().getAlternatives(), "rule__Transaction__Alternatives");
					put(grammarAccess.getRequiredFeatureAccess().getAlternatives(), "rule__RequiredFeature__Alternatives");
					put(grammarAccess.getOneWayTimeOutAccess().getAlternatives(), "rule__OneWayTimeOut__Alternatives");
					put(grammarAccess.getTwoWayTimeOutAccess().getAlternatives(), "rule__TwoWayTimeOut__Alternatives");
					put(grammarAccess.getProtocolAccess().getAlternatives(), "rule__Protocol__Alternatives");
					put(grammarAccess.getTimeUnitAccess().getAlternatives(), "rule__TimeUnit__Alternatives");
					put(grammarAccess.getPatternAccess().getAlternatives(), "rule__Pattern__Alternatives");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getTwoPartVersionStringAccess().getGroup(), "rule__TwoPartVersionString__Group__0");
					put(grammarAccess.getFourPartVersionStringAccess().getGroup(), "rule__FourPartVersionString__Group__0");
					put(grammarAccess.getPartnerAccess().getGroup(), "rule__Partner__Group__0");
					put(grammarAccess.getPartnerAccess().getGroup_6(), "rule__Partner__Group_6__0");
					put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
					put(grammarAccess.getProcessAccess().getGroup_4(), "rule__Process__Group_4__0");
					put(grammarAccess.getPreconditionsAccess().getGroup(), "rule__Preconditions__Group__0");
					put(grammarAccess.getPreconditionsAccess().getGroup_3(), "rule__Preconditions__Group_3__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getEntityStateAccess().getGroup(), "rule__EntityState__Group__0");
					put(grammarAccess.getEntityStateAccess().getGroup_2(), "rule__EntityState__Group_2__0");
					put(grammarAccess.getEntityStateAccess().getGroup_2_2(), "rule__EntityState__Group_2_2__0");
					put(grammarAccess.getPostconditionsAccess().getGroup(), "rule__Postconditions__Group__0");
					put(grammarAccess.getOnProcessSuccessAccess().getGroup(), "rule__OnProcessSuccess__Group__0");
					put(grammarAccess.getOnProcessSuccessAccess().getGroup_3(), "rule__OnProcessSuccess__Group_3__0");
					put(grammarAccess.getOnProcessFailureAccess().getGroup(), "rule__OnProcessFailure__Group__0");
					put(grammarAccess.getOnProcessFailureAccess().getGroup_3(), "rule__OnProcessFailure__Group_3__0");
					put(grammarAccess.getWorkflowAccess().getGroup(), "rule__Workflow__Group__0");
					put(grammarAccess.getWorkflowAccess().getGroup_2(), "rule__Workflow__Group_2__0");
					put(grammarAccess.getWorkflowAccess().getGroup_2_2(), "rule__Workflow__Group_2_2__0");
					put(grammarAccess.getRoleDeclarationsAccess().getGroup(), "rule__RoleDeclarations__Group__0");
					put(grammarAccess.getRoleDeclarationsAccess().getGroup_2(), "rule__RoleDeclarations__Group_2__0");
					put(grammarAccess.getProcessReferenceAccess().getGroup(), "rule__ProcessReference__Group__0");
					put(grammarAccess.getWorkflowBlockAccess().getGroup(), "rule__WorkflowBlock__Group__0");
					put(grammarAccess.getWorkflowBranchAccess().getGroup(), "rule__WorkflowBranch__Group__0");
					put(grammarAccess.getBranchConditionAccess().getGroup(), "rule__BranchCondition__Group__0");
					put(grammarAccess.getTransactionCallAccess().getGroup(), "rule__TransactionCall__Group__0");
					put(grammarAccess.getTransactionCallAccess().getGroup_2(), "rule__TransactionCall__Group_2__0");
					put(grammarAccess.getTransactionCallAccess().getGroup_2_2(), "rule__TransactionCall__Group_2_2__0");
					put(grammarAccess.getTransactionVariantMappingAccess().getGroup(), "rule__TransactionVariantMapping__Group__0");
					put(grammarAccess.getSenderRoleMappingAccess().getGroup(), "rule__SenderRoleMapping__Group__0");
					put(grammarAccess.getReceiverRoleMappingAccess().getGroup(), "rule__ReceiverRoleMapping__Group__0");
					put(grammarAccess.getWorkflowCallAccess().getGroup(), "rule__WorkflowCall__Group__0");
					put(grammarAccess.getWorkflowCallAccess().getGroup_2(), "rule__WorkflowCall__Group_2__0");
					put(grammarAccess.getWorkflowCallAccess().getGroup_2_2(), "rule__WorkflowCall__Group_2_2__0");
					put(grammarAccess.getWorkflowCallAccess().getGroup_5(), "rule__WorkflowCall__Group_5__0");
					put(grammarAccess.getWorkflowVariantMappingAccess().getGroup(), "rule__WorkflowVariantMapping__Group__0");
					put(grammarAccess.getWorkflowRoleMappingAccess().getGroup(), "rule__WorkflowRoleMapping__Group__0");
					put(grammarAccess.getInformTransactionAccess().getGroup(), "rule__InformTransaction__Group__0");
					put(grammarAccess.getInformTransactionAccess().getGroup_2(), "rule__InformTransaction__Group_2__0");
					put(grammarAccess.getInformTransactionAccess().getGroup_2_2(), "rule__InformTransaction__Group_2_2__0");
					put(grammarAccess.getDatagramActionAccess().getGroup(), "rule__DatagramAction__Group__0");
					put(grammarAccess.getVariantMessageMappingsAccess().getGroup(), "rule__VariantMessageMappings__Group__0");
					put(grammarAccess.getVariantMessageMappingsAccess().getGroup_3(), "rule__VariantMessageMappings__Group_3__0");
					put(grammarAccess.getVariantMessageMappingAccess().getGroup(), "rule__VariantMessageMapping__Group__0");
					put(grammarAccess.getVariantMessageMappingAccess().getGroup_3(), "rule__VariantMessageMapping__Group_3__0");
					put(grammarAccess.getMessageMappingAccess().getGroup(), "rule__MessageMapping__Group__0");
					put(grammarAccess.getRequiredFeaturesAccess().getGroup(), "rule__RequiredFeatures__Group__0");
					put(grammarAccess.getRequiredFeaturesAccess().getGroup_3(), "rule__RequiredFeatures__Group_3__0");
					put(grammarAccess.getNotifyTransactionAccess().getGroup(), "rule__NotifyTransaction__Group__0");
					put(grammarAccess.getNotifyTransactionAccess().getGroup_2(), "rule__NotifyTransaction__Group_2__0");
					put(grammarAccess.getNotifyTransactionAccess().getGroup_2_2(), "rule__NotifyTransaction__Group_2_2__0");
					put(grammarAccess.getOneWayActionAccess().getGroup(), "rule__OneWayAction__Group__0");
					put(grammarAccess.getOneWayTimeOutsAccess().getGroup(), "rule__OneWayTimeOuts__Group__0");
					put(grammarAccess.getOneWayTimeOutsAccess().getGroup_3(), "rule__OneWayTimeOuts__Group_3__0");
					put(grammarAccess.getReceiptAckTimeOutAccess().getGroup(), "rule__ReceiptAckTimeOut__Group__0");
					put(grammarAccess.getTimeOutAccess().getGroup(), "rule__TimeOut__Group__0");
					put(grammarAccess.getValidationAckTimeOutAccess().getGroup(), "rule__ValidationAckTimeOut__Group__0");
					put(grammarAccess.getRequestTransactionAccess().getGroup(), "rule__RequestTransaction__Group__0");
					put(grammarAccess.getRequestTransactionAccess().getGroup_2(), "rule__RequestTransaction__Group_2__0");
					put(grammarAccess.getRequestTransactionAccess().getGroup_2_2(), "rule__RequestTransaction__Group_2_2__0");
					put(grammarAccess.getTwoWayActionAccess().getGroup(), "rule__TwoWayAction__Group__0");
					put(grammarAccess.getTwoWayTimeOutsAccess().getGroup(), "rule__TwoWayTimeOuts__Group__0");
					put(grammarAccess.getTwoWayTimeOutsAccess().getGroup_3(), "rule__TwoWayTimeOuts__Group_3__0");
					put(grammarAccess.getTwoWayTimeOutsAccess().getGroup_3_0(), "rule__TwoWayTimeOuts__Group_3_0__0");
					put(grammarAccess.getTwoWayTimeOutsAccess().getGroup_3_1(), "rule__TwoWayTimeOuts__Group_3_1__0");
					put(grammarAccess.getResponseTimeOutAccess().getGroup(), "rule__ResponseTimeOut__Group__0");
					put(grammarAccess.getProtocolReferenceAccess().getGroup(), "rule__ProtocolReference__Group__0");
					put(grammarAccess.getProtocolDeclarationAccess().getGroup(), "rule__ProtocolDeclaration__Group__0");
					put(grammarAccess.getProtocolDeclarationAccess().getGroup_3(), "rule__ProtocolDeclaration__Group_3__0");
					put(grammarAccess.getDomainmodelAccess().getElementsAssignment(), "rule__Domainmodel__ElementsAssignment");
					put(grammarAccess.getImportAccess().getPackageAssignment_1(), "rule__Import__PackageAssignment_1");
					put(grammarAccess.getPackageAccess().getNameAssignment_1(), "rule__Package__NameAssignment_1");
					put(grammarAccess.getPackageAccess().getVersionAssignment_2(), "rule__Package__VersionAssignment_2");
					put(grammarAccess.getPackageAccess().getElementsAssignment_4(), "rule__Package__ElementsAssignment_4");
					put(grammarAccess.getTwoPartVersionStringAccess().getMajorAssignment_0(), "rule__TwoPartVersionString__MajorAssignment_0");
					put(grammarAccess.getTwoPartVersionStringAccess().getMinorAssignment_2(), "rule__TwoPartVersionString__MinorAssignment_2");
					put(grammarAccess.getFourPartVersionStringAccess().getReleaseAssignment_1(), "rule__FourPartVersionString__ReleaseAssignment_1");
					put(grammarAccess.getFourPartVersionStringAccess().getBuildAssignment_3(), "rule__FourPartVersionString__BuildAssignment_3");
					put(grammarAccess.getPartnerAccess().getNameAssignment_1(), "rule__Partner__NameAssignment_1");
					put(grammarAccess.getPartnerAccess().getResponsibilitiesAssignment_5(), "rule__Partner__ResponsibilitiesAssignment_5");
					put(grammarAccess.getPartnerAccess().getResponsibilitiesAssignment_6_1(), "rule__Partner__ResponsibilitiesAssignment_6_1");
					put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
					put(grammarAccess.getProcessAccess().getRolesAssignment_3(), "rule__Process__RolesAssignment_3");
					put(grammarAccess.getProcessAccess().getRolesAssignment_4_1(), "rule__Process__RolesAssignment_4_1");
					put(grammarAccess.getProcessAccess().getDescriptionAssignment_8(), "rule__Process__DescriptionAssignment_8");
					put(grammarAccess.getProcessAccess().getPreconditionsAssignment_9(), "rule__Process__PreconditionsAssignment_9");
					put(grammarAccess.getProcessAccess().getPostconditionsAssignment_10(), "rule__Process__PostconditionsAssignment_10");
					put(grammarAccess.getRoleAccess().getNameAssignment(), "rule__Role__NameAssignment");
					put(grammarAccess.getPreconditionsAccess().getConditionsAssignment_2(), "rule__Preconditions__ConditionsAssignment_2");
					put(grammarAccess.getPreconditionsAccess().getConditionsAssignment_3_1(), "rule__Preconditions__ConditionsAssignment_3_1");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getStatesAssignment_3(), "rule__Entity__StatesAssignment_3");
					put(grammarAccess.getEntityStateAccess().getNameAssignment_1(), "rule__EntityState__NameAssignment_1");
					put(grammarAccess.getEntityStateAccess().getTransitionsAssignment_2_1(), "rule__EntityState__TransitionsAssignment_2_1");
					put(grammarAccess.getEntityStateAccess().getTransitionsAssignment_2_2_1(), "rule__EntityState__TransitionsAssignment_2_2_1");
					put(grammarAccess.getEntityStateTransitionAccess().getSuccessorAssignment(), "rule__EntityStateTransition__SuccessorAssignment");
					put(grammarAccess.getPostconditionsAccess().getSuccessAssignment_3(), "rule__Postconditions__SuccessAssignment_3");
					put(grammarAccess.getPostconditionsAccess().getFailureAssignment_4(), "rule__Postconditions__FailureAssignment_4");
					put(grammarAccess.getOnProcessSuccessAccess().getResultsAssignment_2(), "rule__OnProcessSuccess__ResultsAssignment_2");
					put(grammarAccess.getOnProcessSuccessAccess().getResultsAssignment_3_1(), "rule__OnProcessSuccess__ResultsAssignment_3_1");
					put(grammarAccess.getOnProcessFailureAccess().getResultsAssignment_2(), "rule__OnProcessFailure__ResultsAssignment_2");
					put(grammarAccess.getOnProcessFailureAccess().getResultsAssignment_3_1(), "rule__OnProcessFailure__ResultsAssignment_3_1");
					put(grammarAccess.getWorkflowAccess().getNameAssignment_1(), "rule__Workflow__NameAssignment_1");
					put(grammarAccess.getWorkflowAccess().getVariantsAssignment_2_1(), "rule__Workflow__VariantsAssignment_2_1");
					put(grammarAccess.getWorkflowAccess().getVariantsAssignment_2_2_1(), "rule__Workflow__VariantsAssignment_2_2_1");
					put(grammarAccess.getWorkflowAccess().getRolesAssignment_3(), "rule__Workflow__RolesAssignment_3");
					put(grammarAccess.getWorkflowAccess().getContentsAssignment_4(), "rule__Workflow__ContentsAssignment_4");
					put(grammarAccess.getWorkflowVariantAccess().getNameAssignment(), "rule__WorkflowVariant__NameAssignment");
					put(grammarAccess.getRoleDeclarationsAccess().getRolesAssignment_1(), "rule__RoleDeclarations__RolesAssignment_1");
					put(grammarAccess.getRoleDeclarationsAccess().getRolesAssignment_2_1(), "rule__RoleDeclarations__RolesAssignment_2_1");
					put(grammarAccess.getProcessReferenceAccess().getImplementsAssignment_1(), "rule__ProcessReference__ImplementsAssignment_1");
					put(grammarAccess.getWorkflowBlockAccess().getElementsAssignment_1(), "rule__WorkflowBlock__ElementsAssignment_1");
					put(grammarAccess.getWorkflowBlockAccess().getElementsAssignment_2(), "rule__WorkflowBlock__ElementsAssignment_2");
					put(grammarAccess.getEndPointAccess().getNameAssignment_0(), "rule__EndPoint__NameAssignment_0");
					put(grammarAccess.getEndPointAccess().getNameAssignment_1(), "rule__EndPoint__NameAssignment_1");
					put(grammarAccess.getWorkflowBranchAccess().getConditionsAssignment_2(), "rule__WorkflowBranch__ConditionsAssignment_2");
					put(grammarAccess.getBranchConditionAccess().getContentsAssignment_4(), "rule__BranchCondition__ContentsAssignment_4");
					put(grammarAccess.getTransactionCallAccess().getNameAssignment_1(), "rule__TransactionCall__NameAssignment_1");
					put(grammarAccess.getTransactionCallAccess().getVariantsAssignment_2_1(), "rule__TransactionCall__VariantsAssignment_2_1");
					put(grammarAccess.getTransactionCallAccess().getVariantsAssignment_2_2_1(), "rule__TransactionCall__VariantsAssignment_2_2_1");
					put(grammarAccess.getTransactionCallAccess().getSenderAssignment_4(), "rule__TransactionCall__SenderAssignment_4");
					put(grammarAccess.getTransactionCallAccess().getReceiverAssignment_6(), "rule__TransactionCall__ReceiverAssignment_6");
					put(grammarAccess.getTransactionVariantMappingAccess().getParameterAssignment_0(), "rule__TransactionVariantMapping__ParameterAssignment_0");
					put(grammarAccess.getTransactionVariantMappingAccess().getValueAssignment_2(), "rule__TransactionVariantMapping__ValueAssignment_2");
					put(grammarAccess.getSenderRoleMappingAccess().getParameterAssignment_0(), "rule__SenderRoleMapping__ParameterAssignment_0");
					put(grammarAccess.getSenderRoleMappingAccess().getValueAssignment_2(), "rule__SenderRoleMapping__ValueAssignment_2");
					put(grammarAccess.getReceiverRoleMappingAccess().getParameterAssignment_0(), "rule__ReceiverRoleMapping__ParameterAssignment_0");
					put(grammarAccess.getReceiverRoleMappingAccess().getValueAssignment_2(), "rule__ReceiverRoleMapping__ValueAssignment_2");
					put(grammarAccess.getWorkflowCallAccess().getNameAssignment_1(), "rule__WorkflowCall__NameAssignment_1");
					put(grammarAccess.getWorkflowCallAccess().getVariantsAssignment_2_1(), "rule__WorkflowCall__VariantsAssignment_2_1");
					put(grammarAccess.getWorkflowCallAccess().getVariantsAssignment_2_2_1(), "rule__WorkflowCall__VariantsAssignment_2_2_1");
					put(grammarAccess.getWorkflowCallAccess().getRolesAssignment_4(), "rule__WorkflowCall__RolesAssignment_4");
					put(grammarAccess.getWorkflowCallAccess().getRolesAssignment_5_1(), "rule__WorkflowCall__RolesAssignment_5_1");
					put(grammarAccess.getWorkflowVariantMappingAccess().getParameterAssignment_0(), "rule__WorkflowVariantMapping__ParameterAssignment_0");
					put(grammarAccess.getWorkflowVariantMappingAccess().getValueAssignment_2(), "rule__WorkflowVariantMapping__ValueAssignment_2");
					put(grammarAccess.getWorkflowRoleMappingAccess().getParameterAssignment_0(), "rule__WorkflowRoleMapping__ParameterAssignment_0");
					put(grammarAccess.getWorkflowRoleMappingAccess().getValueAssignment_2(), "rule__WorkflowRoleMapping__ValueAssignment_2");
					put(grammarAccess.getInformTransactionAccess().getPatternAssignment_0(), "rule__InformTransaction__PatternAssignment_0");
					put(grammarAccess.getInformTransactionAccess().getNameAssignment_1(), "rule__InformTransaction__NameAssignment_1");
					put(grammarAccess.getInformTransactionAccess().getVariantsAssignment_2_1(), "rule__InformTransaction__VariantsAssignment_2_1");
					put(grammarAccess.getInformTransactionAccess().getVariantsAssignment_2_2_1(), "rule__InformTransaction__VariantsAssignment_2_2_1");
					put(grammarAccess.getInformTransactionAccess().getSendActionAssignment_5(), "rule__InformTransaction__SendActionAssignment_5");
					put(grammarAccess.getInformTransactionAccess().getPostconditionsAssignment_6(), "rule__InformTransaction__PostconditionsAssignment_6");
					put(grammarAccess.getTransactionVariantAccess().getNameAssignment(), "rule__TransactionVariant__NameAssignment");
					put(grammarAccess.getDatagramActionAccess().getMessagesAssignment_2(), "rule__DatagramAction__MessagesAssignment_2");
					put(grammarAccess.getDatagramActionAccess().getRequiresAssignment_3(), "rule__DatagramAction__RequiresAssignment_3");
					put(grammarAccess.getVariantMessageMappingsAccess().getVariantsAssignment_2(), "rule__VariantMessageMappings__VariantsAssignment_2");
					put(grammarAccess.getVariantMessageMappingsAccess().getVariantsAssignment_3_1(), "rule__VariantMessageMappings__VariantsAssignment_3_1");
					put(grammarAccess.getVariantMessageMappingAccess().getVariantAssignment_0(), "rule__VariantMessageMapping__VariantAssignment_0");
					put(grammarAccess.getVariantMessageMappingAccess().getMappingsAssignment_2(), "rule__VariantMessageMapping__MappingsAssignment_2");
					put(grammarAccess.getVariantMessageMappingAccess().getMappingsAssignment_3_1(), "rule__VariantMessageMapping__MappingsAssignment_3_1");
					put(grammarAccess.getMessageMappingAccess().getParameterAssignment_0(), "rule__MessageMapping__ParameterAssignment_0");
					put(grammarAccess.getMessageMappingAccess().getValueAssignment_2(), "rule__MessageMapping__ValueAssignment_2");
					put(grammarAccess.getRequiredFeaturesAccess().getFeaturesAssignment_2(), "rule__RequiredFeatures__FeaturesAssignment_2");
					put(grammarAccess.getRequiredFeaturesAccess().getFeaturesAssignment_3_1(), "rule__RequiredFeatures__FeaturesAssignment_3_1");
					put(grammarAccess.getAuthorizationFeatureAccess().getAuthorizationAssignment(), "rule__AuthorizationFeature__AuthorizationAssignment");
					put(grammarAccess.getNonRepudiationFeatureAccess().getNonrepudiationAssignment(), "rule__NonRepudiationFeature__NonrepudiationAssignment");
					put(grammarAccess.getNotifyTransactionAccess().getPatternAssignment_0(), "rule__NotifyTransaction__PatternAssignment_0");
					put(grammarAccess.getNotifyTransactionAccess().getNameAssignment_1(), "rule__NotifyTransaction__NameAssignment_1");
					put(grammarAccess.getNotifyTransactionAccess().getVariantsAssignment_2_1(), "rule__NotifyTransaction__VariantsAssignment_2_1");
					put(grammarAccess.getNotifyTransactionAccess().getVariantsAssignment_2_2_1(), "rule__NotifyTransaction__VariantsAssignment_2_2_1");
					put(grammarAccess.getNotifyTransactionAccess().getSendActionAssignment_5(), "rule__NotifyTransaction__SendActionAssignment_5");
					put(grammarAccess.getNotifyTransactionAccess().getPostconditionsAssignment_6(), "rule__NotifyTransaction__PostconditionsAssignment_6");
					put(grammarAccess.getOneWayActionAccess().getMessagesAssignment_1(), "rule__OneWayAction__MessagesAssignment_1");
					put(grammarAccess.getOneWayActionAccess().getRequiresAssignment_2(), "rule__OneWayAction__RequiresAssignment_2");
					put(grammarAccess.getOneWayActionAccess().getTimeoutsAssignment_3(), "rule__OneWayAction__TimeoutsAssignment_3");
					put(grammarAccess.getOneWayActionAccess().getRetriesAssignment_6(), "rule__OneWayAction__RetriesAssignment_6");
					put(grammarAccess.getOneWayTimeOutsAccess().getTimeoutsAssignment_2(), "rule__OneWayTimeOuts__TimeoutsAssignment_2");
					put(grammarAccess.getOneWayTimeOutsAccess().getTimeoutsAssignment_3_1(), "rule__OneWayTimeOuts__TimeoutsAssignment_3_1");
					put(grammarAccess.getReceiptAckTimeOutAccess().getTimeoutAssignment_2(), "rule__ReceiptAckTimeOut__TimeoutAssignment_2");
					put(grammarAccess.getTimeOutAccess().getValueAssignment_0(), "rule__TimeOut__ValueAssignment_0");
					put(grammarAccess.getTimeOutAccess().getUnitAssignment_1(), "rule__TimeOut__UnitAssignment_1");
					put(grammarAccess.getValidationAckTimeOutAccess().getTimeoutAssignment_2(), "rule__ValidationAckTimeOut__TimeoutAssignment_2");
					put(grammarAccess.getRequestTransactionAccess().getPatternAssignment_0(), "rule__RequestTransaction__PatternAssignment_0");
					put(grammarAccess.getRequestTransactionAccess().getNameAssignment_1(), "rule__RequestTransaction__NameAssignment_1");
					put(grammarAccess.getRequestTransactionAccess().getVariantsAssignment_2_1(), "rule__RequestTransaction__VariantsAssignment_2_1");
					put(grammarAccess.getRequestTransactionAccess().getVariantsAssignment_2_2_1(), "rule__RequestTransaction__VariantsAssignment_2_2_1");
					put(grammarAccess.getRequestTransactionAccess().getSendActionAssignment_5(), "rule__RequestTransaction__SendActionAssignment_5");
					put(grammarAccess.getRequestTransactionAccess().getReceiveActionAssignment_7(), "rule__RequestTransaction__ReceiveActionAssignment_7");
					put(grammarAccess.getRequestTransactionAccess().getPostconditionsAssignment_8(), "rule__RequestTransaction__PostconditionsAssignment_8");
					put(grammarAccess.getTwoWayActionAccess().getMessagesAssignment_1(), "rule__TwoWayAction__MessagesAssignment_1");
					put(grammarAccess.getTwoWayActionAccess().getRequiresAssignment_2(), "rule__TwoWayAction__RequiresAssignment_2");
					put(grammarAccess.getTwoWayActionAccess().getTimeoutsAssignment_3(), "rule__TwoWayAction__TimeoutsAssignment_3");
					put(grammarAccess.getTwoWayActionAccess().getRetriesAssignment_6(), "rule__TwoWayAction__RetriesAssignment_6");
					put(grammarAccess.getTwoWayTimeOutsAccess().getTimeoutsAssignment_2(), "rule__TwoWayTimeOuts__TimeoutsAssignment_2");
					put(grammarAccess.getTwoWayTimeOutsAccess().getTimeoutsAssignment_3_0_1(), "rule__TwoWayTimeOuts__TimeoutsAssignment_3_0_1");
					put(grammarAccess.getTwoWayTimeOutsAccess().getTimeoutsAssignment_3_1_1(), "rule__TwoWayTimeOuts__TimeoutsAssignment_3_1_1");
					put(grammarAccess.getResponseTimeOutAccess().getTimeoutAssignment_2(), "rule__ResponseTimeOut__TimeoutAssignment_2");
					put(grammarAccess.getProtocolReferenceAccess().getNameAssignment_1(), "rule__ProtocolReference__NameAssignment_1");
					put(grammarAccess.getProtocolDeclarationAccess().getNameAssignment_1(), "rule__ProtocolDeclaration__NameAssignment_1");
					put(grammarAccess.getProtocolDeclarationAccess().getMessagesAssignment_3_1(), "rule__ProtocolDeclaration__MessagesAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.x.xocl.ui.contentassist.antlr.internal.InternalXOCLParser typedParser = (com.x.xocl.ui.contentassist.antlr.internal.InternalXOCLParser) parser;
			typedParser.entryRuleDomainmodel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public XOCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XOCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
