<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domainmodel"
    nsURI="http://x.com/xocl/XOCL" nsPrefix="domainmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Domainmodel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//TopLevelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Import" eSuperTypes="#//TopLevelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//TopLevelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="version" eType="#//VersionString"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PackageElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionString"/>
  <eClassifiers xsi:type="ecore:EClass" name="TwoPartVersionString" eSuperTypes="#//VersionString #//FourPartVersionString">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="major" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="release" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="build" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FourPartVersionString" eSuperTypes="#//VersionString"/>
  <eClassifiers xsi:type="ecore:EClass" name="PackageElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partner" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibilities" unique="false"
        upperBound="-1" eType="#//ProcessRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//ProcessRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" eType="#//Preconditions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postconditions" eType="#//Postconditions"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessRole" eSuperTypes="#//WorkflowRoleReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//ProcessRole #//WorkflowRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preconditions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" unique="false"
        upperBound="-1" eType="#//EntityState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//EntityState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//EntityStateTransition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityStateTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="successor" eType="#//EntityState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Postconditions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="success" eType="#//OnProcessSuccess"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure" eType="#//OnProcessFailure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnProcessResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" unique="false"
        upperBound="-1" eType="#//EntityState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnProcessSuccess" eSuperTypes="#//OnProcessResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnProcessFailure" eSuperTypes="#//OnProcessResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//WorkflowVariant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" eType="#//WorkflowRoles"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" eType="#//WorkflowBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowVariant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowRoles"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleDeclarations" eSuperTypes="#//WorkflowRoles">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//WorkflowRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowRole" eSuperTypes="#//WorkflowRoleReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessReference" eSuperTypes="#//WorkflowRoles">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" eType="#//Process"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowBranch" eSuperTypes="#//WorkflowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//BranchCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" eType="#//WorkflowBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowAction" eSuperTypes="#//WorkflowElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionCall" eSuperTypes="#//WorkflowAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Transaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//TransactionVariantMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" eType="#//SenderRoleMapping"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//ReceiverRoleMapping"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionVariantMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//TransactionVariant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//WorkflowVariant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SenderRoleMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//WorkflowRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiverRoleMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//WorkflowRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowCall" eSuperTypes="#//WorkflowAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Workflow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//WorkflowVariantMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//WorkflowRoleMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowVariantMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//WorkflowVariant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//WorkflowVariant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowRoleMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//WorkflowRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//WorkflowRoleReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowRoleReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction" eSuperTypes="#//PackageElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//TransactionVariant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postconditions" eType="#//Postconditions"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformTransaction" eSuperTypes="#//Transaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendAction" eType="#//DatagramAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransactionVariant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatagramAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" eType="#//VariantMessageMappings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" eType="#//RequiredFeatures"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariantMessageMappings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//VariantMessageMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariantMessageMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variant" eType="#//TransactionVariant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//MessageMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredFeatures">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//RequiredFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthorizationFeature" eSuperTypes="#//RequiredFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NonRepudiationFeature" eSuperTypes="#//RequiredFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonrepudiation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotifyTransaction" eSuperTypes="#//Transaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendAction" eType="#//OneWayAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneWayAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" eType="#//VariantMessageMappings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" eType="#//RequiredFeatures"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeouts" eType="#//OneWayTimeOuts"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneWayTimeOuts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeouts" upperBound="-1"
        eType="#//OneWayTimeOut" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OneWayTimeOut" eSuperTypes="#//TwoWayTimeOut"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiptAckTimeOut" eSuperTypes="#//OneWayTimeOut"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeOut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//TimeUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
    <eLiterals name="SECONDS" literal="s"/>
    <eLiterals name="MINUTES" value="1" literal="m"/>
    <eLiterals name="HOURS" value="2" literal="h"/>
    <eLiterals name="DAYS" value="3" literal="d"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationAckTimeOut" eSuperTypes="#//OneWayTimeOut"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Pattern">
    <eLiterals name="Response" literal="response"/>
    <eLiterals name="Confirm" value="1" literal="confirm"/>
    <eLiterals name="Query" value="2" literal="query"/>
    <eLiterals name="Obligation" value="3" literal="obligation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestTransaction" eSuperTypes="#//Transaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendAction" eType="#//TwoWayAction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveAction" eType="#//OneWayAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TwoWayAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" eType="#//VariantMessageMappings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" eType="#//RequiredFeatures"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeouts" eType="#//TwoWayTimeOuts"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TwoWayTimeOuts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeouts" upperBound="-1"
        eType="#//TwoWayTimeOut" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TwoWayTimeOut">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeout" eType="#//TimeOut"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseTimeOut" eSuperTypes="#//TwoWayTimeOut"/>
  <eClassifiers xsi:type="ecore:EClass" name="Protocol" eSuperTypes="#//PackageElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolReference" eSuperTypes="#//Protocol"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProtocolDeclaration" eSuperTypes="#//Protocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messages" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
