/*
* generated by Xtext
*/
package com.x.xocl.ui.contentassist;

import com.x.xocl.ui.contentassist.AbstractXOCLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XOCLProposalProvider extends AbstractXOCLProposalProvider {

}
