/*
* generated by Xtext
*/
package com.x.xocl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.x.xocl.services.XOCLGrammarAccess;

public class XOCLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XOCLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.x.xocl.parser.antlr.internal.InternalXOCLParser createParser(XtextTokenStream stream) {
		return new com.x.xocl.parser.antlr.internal.InternalXOCLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}
	
	public XOCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XOCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
