/*
* generated by Xtext
*/
package com.x.xocl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XOCLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.x.xocl.ui.internal.XOCLActivator.getInstance().getInjector("com.x.xocl.XOCL");
	}
	
}
