/*
 * generated by Xtext
 */
package com.x.xocl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XOCLUiModule extends com.x.xocl.ui.AbstractXOCLUiModule {
	public XOCLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
